version: '3'

services:

  notificator:
    build:
      context: ./notificator
      dockerfile: Dockerfile
    image: node-image
    container_name: notificator
    networks:
      - nodenet
    ports:
      - "3000:4000"
    # depends_on:
    #   - mongodb

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: node-api-image
    container_name: api
    networks:
      - nodenet
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongodb

  # mongodb:
  #   container_name: mongodb
  #   restart: unless-stopped
  #   image: mongo:4.4.6
  #   env_file: ./.env
  #   volumes:
  #     - ~/mongo:/data/mongodb
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_USER=$MONGODB_USER
  #     - DB_PASSWORD=$MONGODB_PASSWORD
  #     - DB_NAME=$MONGODB_DATABASE
  #     - DB_PORT=$MONGODB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - nodenet

  app:
    container_name: app-dev
    image: app-dev
    build:
      context: ./react-admin-dashboard
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000

networks:
  nodenet:
    driver: bridge